name: "PR Checker"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t pr_checker . --no-cache

      # Step 3: Run commands inside the built container
      - name: Run script inside container
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm -e GH_TOKEN=$GH_TOKEN pr_checker bash -c "/home/src/pr_checker.sh"
